# fly.toml app configuration file generated for timelyst-front on 2025-08-09T19:10:04-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'timelyst-front'
primary_region = 'iad'

[build]
  [build.args]
    CLIENT_ID = "${CLIENT_ID}"
    CLIENT_SECRET = "${CLIENT_SECRET}"
    GOOGLE_OATH_URL = "${GOOGLE_OATH_URL}"
    GOOGLE_OATH2_TOKEN_URL = "${GOOGLE_OATH2_TOKEN_URL}"
    BACKEND_GOOGLE_CALLBACK = "${BACKEND_GOOGLE_CALLBACK}"
    BACKEND_FETCH_GOOGLE_CALENDARS = "${BACKEND_FETCH_GOOGLE_CALENDARS}"
    BACKEND_SAVE_SELECTED_GOOGLE_CALENDARS = "${BACKEND_SAVE_SELECTED_GOOGLE_CALENDARS}"
    REDIRECT_URI = "${REDIRECT_URI}"
    FRONTEND_URL = "${FRONTEND_URL}"
    BACKEND_URL = "${BACKEND_URL}"
    BACKEND_URL_GRAPHQL = "${BACKEND_URL_GRAPHQL}"

[env]
  PORT = '7357'

[http_service]
  internal_port = 7357
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1