# fly.toml app configuration file generated for timelyst-front on 2025-08-09T19:10:04-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'timelyst-front'
primary_region = 'iad'

[build]
  [build.args]
    GOOGLE_CLIENT_ID = "${GOOGLE_CLIENT_ID}"
    GOOGLE_CLIENT_SECRET = "${GOOGLE_CLIENT_SECRET}"
    GOOGLE_OAUTH_URL = "${GOOGLE_OAUTH_URL}"
    GOOGLE_OAUTH2_TOKEN_URL = "${GOOGLE_OAUTH2_TOKEN_URL}"
    BACKEND_GOOGLE_CALENDAR = "${BACKEND_GOOGLE_CALENDAR}"
    BACKEND_FETCH_GOOGLE_CALENDARS = "${BACKEND_FETCH_GOOGLE_CALENDARS}"
    BACKEND_URL = "${BACKEND_URL}"
    BACKEND_URL_GRAPHQL = "${BACKEND_URL_GRAPHQL}"
    FRONTEND_URL = "${FRONTEND_URL}"
    REDIRECT_URL = "${REDIRECT_URL}"

[env]
  PORT = '7357'

[http_service]
  internal_port = 7357
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1